export const PARTIDOS = [
  { orden: 1,  codigo: 'AEV', nombre: 'Alianza Electoral Venceremos',           color: '#1B4FBE' },
  { orden: 2,  codigo: 'PPP', nombre: 'Partido Patriótico del Perú',             color: '#C8102E' },
  { orden: 3,  codigo: 'PCO', nombre: 'Partido Cívico Obras',                    color: '#D97706' },
  { orden: 4,  codigo: 'FPA', nombre: 'Frente Popular Agrícola del Perú (FREPAP)', color: '#1A7A3E' },
  { orden: 5,  codigo: 'PDV', nombre: 'Partido Demócrata Verde',                 color: '#2E7D32' },
  { orden: 6,  codigo: 'PBG', nombre: 'Partido del Buen Gobierno',               color: '#E65100' },
  { orden: 7,  codigo: 'PPA', nombre: 'Perú Acción',                             color: '#6A1B9A' },
  { orden: 8,  codigo: 'PRI', nombre: 'Partido Político PRIN',                   color: '#B71C1C' },
  { orden: 9,  codigo: 'PRO', nombre: 'Progresemos',                             color: '#00695C' },
  { orden: 10, codigo: 'SIC', nombre: 'Partido SÍCREO',                          color: '#37474F' },
  { orden: 11, codigo: 'PPT', nombre: 'Partido País para todos',                 color: '#1565C0' },
  { orden: 12, codigo: 'FE2', nombre: 'Frente de la Esperanza 2021',             color: '#4527A0' },
  { orden: 13, codigo: 'PPL', nombre: 'Partido Político Perú Libre',             color: '#C62828' },
  { orden: 14, codigo: 'CXP', nombre: 'Ciudadanos por el Perú',                  color: '#0277BD' },
  { orden: 15, codigo: 'PLG', nombre: 'Primero La Gente',                        color: '#F9A825' },
  { orden: 16, codigo: 'JPP', nombre: 'Juntos por el Perú',                      color: '#558B2F' },
  { orden: 17, codigo: 'PDM', nombre: 'Podemos Perú',                            color: '#1976D2' },
  { orden: 18, codigo: 'PDF', nombre: 'Partido Democrático Federal',             color: '#AD1457' },
  { orden: 19, codigo: 'PFP', nombre: 'Fe en el Perú',                           color: '#E65100' },
  { orden: 20, codigo: 'IDE', nombre: 'Integridad Democrática',                  color: '#283593' },
  { orden: 21, codigo: 'FPO', nombre: 'Fuerza Popular',                          color: '#F57F17' },
  { orden: 22, codigo: 'APP', nombre: 'Alianza para el Progreso',                color: '#1B5E20' },
  { orden: 23, codigo: 'COP', nombre: 'Partido Cooperación Popular',             color: '#880E4F' },
  { orden: 24, codigo: 'AHN', nombre: 'Ahora Nación – AN',                       color: '#BF360C' },
  { orden: 25, codigo: 'PLP', nombre: 'Partido Libertad Popular',                color: '#4A148C' },
  { orden: 26, codigo: 'UCD', nombre: 'Un camino diferente',                     color: '#006064' },
  { orden: 27, codigo: 'AVP', nombre: 'Avanza País',                             color: '#E53935' },
  { orden: 28, codigo: 'PPM', nombre: 'Partido Perú Moderno',                    color: '#0277BD' },
  { orden: 29, codigo: 'PPR', nombre: 'Partido Perú Primero',                    color: '#2E7D32' },
  { orden: 30, codigo: 'SLP', nombre: 'Salvemos al Perú',                        color: '#C62828' },
  { orden: 31, codigo: 'SPP', nombre: 'Partido Somos Perú',                      color: '#1565C0' },
  { orden: 32, codigo: 'APR', nombre: 'Partido Aprista Peruano (APRA)',          color: '#B71C1C' },
  { orden: 33, codigo: 'RNP', nombre: 'Renovación Popular',                      color: '#0D47A1' },
  { orden: 34, codigo: 'DUP', nombre: 'Partido Demócrata Unido Perú',            color: '#1A237E' },
  { orden: 35, codigo: 'FYL', nombre: 'Fuerza y Libertad',                       color: '#E65100' },
  { orden: 36, codigo: 'PTE', nombre: 'Partido de los Trabajadores y Emprendedores PTE-Perú', color: '#1B5E20' },
  { orden: 37, codigo: 'UNA', nombre: 'Unidad Nacional',                         color: '#37474F' },
  { orden: 38, codigo: 'PMO', nombre: 'Partido Morado',                          color: '#6A1B9A' },
]

export const CATEGORIAS = [
  { id: 1, codigo: 'PRES',  nombre: 'Presidente y Vicepresidente', color: '#C8102E', maxPref: 0 },
  { id: 2, codigo: 'SEN_N', nombre: 'Senadores — Nivel Nacional',   color: '#1B4FBE', maxPref: 2 },
  { id: 3, codigo: 'SEN_R', nombre: 'Senadores — Nivel Regional',   color: '#1A7A3E', maxPref: 2 },
  { id: 4, codigo: 'DIP',   nombre: 'Diputados',                    color: '#D97706', maxPref: 2 },
  { id: 5, codigo: 'PARL',  nombre: 'Parlamento Andino',            color: '#6A1B9A', maxPref: 1 },
]
